[package]
name = "wasm"
version = "0.1.0"
authors = ["Alex Macleod <alex@macleod.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"

[workspace]
members = ["gen"]
