[package]
name = "utf"
version = "0.0.0"
authors = ["Alex Macleod <alex@macleod.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = []
gen = ["leb128", "ucd-raw"]

[dependencies]
wasm-bindgen = "0.2"
leb128 = { version = "0.2", optional = true }
ucd-raw = { version = "0.5", optional = true }