[package]
name = "utf"
version = "0.0.0"
authors = ["Alex Macleod <alex@macleod.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
leb128 = "0.2"
ucd-raw = "0.5"