[package]
name = "general-suffix"
version = "0.1.0"
authors = ["Alex Macleod <alex@macleod.io>"]

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "gen"
path = "src/bin/gen.rs"
required-features = ["gen"]

[features]
gen = ["ucd-raw"]

[dependencies]
ucd-raw = { version = "0.5", optional = true }
wee_alloc = "0.4"
