[package]
name = "server"
version = "0.1.0"
authors = ["Alex Macleod <alex@macleod.io>"]
edition = "2018"
publish = false

[dependencies]
askama = { version = "0.9", features = ["with-rocket"] }
rocket = { version = "0.4", default-features = false }
