[package]
name = "wasm"
version = "0.1.0"
authors = ["Alex Macleod <alex@macleod.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
bincode = "1"
console_error_panic_hook = "0.1"
itertools = "0.10"
shared = { path = "../shared" }
wasm-bindgen = "0.2"
