name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          yarn install

      - name: Build
        run: |
          yarn gen
          yarn wasm
          yarn lint --max-warnings 0
          yarn build

      - name: Setup SSH
        env:
          id_ed25519: ${{ secrets.id_ed25519 }}
        run: |
          mkdir ~/.ssh
          echo "$id_ed25519" > ~/.ssh/id_ed25519
          echo 'macleod.io ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG6mDh6L36JYQDYRkVk6ZyEmVlkTxEe8OUwHT2X18RvU' > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy
        run: rsync -rtv --delete-after dist/ deploy@macleod.io:/var/www/utf/
