name: Deploy

on:
  push:
    branches: deploy
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          yarn install
      - name: Build
        run: |
          yarn gen
          yarn build
          yarn webpack
      - name: Deploy
        run: tree
