name: Main

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - run: yarn install
    - run: yarn lint
    - run: yarn gen
    - run: yarn build
    - run: yarn webpack
