name: Main

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Generate search index
      run: yarn gen
    - name: Build WASM
      run: yarn build
    - name: Webpack
      run: yarn webpack
