name: Main

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
        key: cargo-bin-${{ github.run_id }}
        restore-keys: cargo-bin-

    - run: rustup self update
    - run: cargo install wasm-bindgen-cli

    - run: yarn install
    - run: yarn gen
    - run: yarn wasm
    # - run: yarn lint
    - run: yarn build
