name: Main

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          target
        key: cargo-${{ github.run_id }}
        restore-keys: cargo-

    - run: rustup self update
    - run: cargo install wasm-bindgen-cli

    - run: cargo test --all

    - run: yarn install
    - run: yarn gen
    - run: yarn wasm
    # - run: yarn lint
    - run: yarn build
