name: Main

on: push

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
        key: cargo-${{ github.run_id }}
        restore-keys: |
          cargo-

    - run: cargo install wasm-bindgen-cli

    - run: yarn install
    - run: yarn gen
    - run: yarn wasm
    - run: yarn lint
    - run: yarn build

    - run: cargo test --all
